[package]
name = "trasher"
version = "1.7.3"
authors = ["Clément Nerma <clement.nerma@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "A small command-line utility to replace 'rm' and 'del' by a trash system"
readme = "README.md"
repository = "https://github.com/ClementNerma/Trasher"

[dependencies]
clap = "3.0.0-beta.4"
chrono = "0.4.19"
regex = "1.5.4"
lazy_static = "1.4.0"
crc-any = "2.3.12"
base64 = "0.13.0"
fs_extra = "1.2.0"
indicatif = "0.16.2"

[[bin]]
name = "trasher"
path = "src/main.rs"
