[package]
name = "trasher"
version = "2.0.5"
authors = ["Clément Nerma <clement.nerma@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
description = "A small command-line utility to replace 'rm' and 'del' by a trash system"
readme = "README.md"
repository = "https://github.com/ClementNerma/Trasher"

[[bin]]
name = "trasher"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.4", features = ["derive"] }
chrono = "0.4.31"
regex = "1.9.5"
crc-any = "2.4.3"
base64 = "0.21.4"
fs_extra = "1.3.0"
indicatif = "0.17.7"
once_cell = "1.18.0"
anyhow = "1.0.75"
