[package]
name = "trasher"
version = "2.0.5"
authors = ["Clément Nerma <clement.nerma@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
description = "A small command-line utility to replace 'rm' and 'del' by a trash system"
readme = "README.md"
repository = "https://github.com/ClementNerma/Trasher"

[dependencies]
clap = { version = "4.2.4", features = ["derive"] }
chrono = "0.4.24"
regex = "1.8.1"
crc-any = "2.4.3"
base64 = "0.21.0"
fs_extra = "1.3.0"
indicatif = "0.17.3"
once_cell = "1.17.1"

[[bin]]
name = "trasher"
path = "src/main.rs"

[profile.dist]
inherits = "release"
lto = "thin"

[workspace.metadata.dist]
targets = ["x86_64-unknown-linux-gnu"]
