[package]
name = "trasher"
version = "1.0.0"
authors = ["Clément Nerma <clement.nerma@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "A small command-line utility to replace 'rm' and 'del' by a trash system"
repository = "https://github.com/ClementNerma/Trasher"

[dependencies]
clap = "3.0.0-beta.1"
chrono = "0.4.12"
regex = "1.3.9"
lazy_static = "1.4.0"
crc-any = "2.3.5"
base64 = "0.12.3"

[[bin]]
name = "trasher"
path = "src/main.rs"